[tool.nitpick]
# Use the default style and override some things (like the Python version)
style = ["https://raw.githubusercontent.com/andreoliwa/nitpick/develop/nitpick-style.toml"]

[tool.poetry]
name = "scrapy-tegenaria"
version = "0.1.0"
description = "ğŸ•·ğŸ•¸ Spiders to crawl ads of houses and apartments. ğŸ ğŸ¢"
authors = ["Augusto W. Andreoli <andreoliwa@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
scrapy = "*"
googlemaps = "*"
keyring = "*"
requests = "*"
imapclient = "*"
arrow = "*"
marshmallow = "*"
click = "*"
plumbum = "*"
prettyconf = "*"
flask = "*"
markupsafe = "*"
werkzeug = "*"
"jinja2" = "*"
itsdangerous = "*"
flask-admin = "*"
flask-marshmallow = "*"
flask-sqlalchemy = "*"
sqlalchemy = "*"
"psycopg2" = "*"
marshmallow-sqlalchemy = "*"
flask-migrate = "*"
flask-wtf = "*"
wtforms = "*"
gunicorn = "*"
toml = "*"

[tool.poetry.dev-dependencies]
flask-debugtoolbar = "*"
flask-script = "*"
pytest = "*"
pytest-runfailed = "*"
webtest = "*"
factory-boy = "*"
faker = "*"
ipdb = "*"
coverage = "*"
pytest-cov = "*"
sphinx = "*"
ipython = "*"
pylint = "*"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
